version: "3.9"
services:
  stats-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URI=mysql+pymysql://springstudent:springstudent@db/HealthTrackerProgress
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: HealthTrackerProgress
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
